# Generated by Django 3.2.15 on 2022-09-22 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, unique=True, verbose_name='адрес')),
                ('created_add', models.TimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('lon', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(-180), django.core.validators.MinValueValidator(180)], verbose_name='Координата адреса (Долгота)')),
                ('lat', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(-90), django.core.validators.MinValueValidator(90)], verbose_name='Координата адреса (Широта)')),
            ],
            options={
                'verbose_name': 'Адрес заказа',
                'verbose_name_plural': 'Адреса заказов',
            },
        ),
    ]
