#!/bin/bash 

echo "Обновляю зависимости"
source venv/bin/activate
pip3 install -r requirements.txt
echo "Зависимости обновлены"

echo "Обновляю миграции"
python3 manage.py migrate
echo "Миграции обновлены"

echo "Собираю статику"
python3 manage.py collectstatic
echo "Статика собрана"

echo "Собираю JS"
./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
echo "JS собран"

deactivate

echo "Перезапускаю Systemd star-burger"
systemctl reload star-burger
echo "Информирую rollbar"

export $(cat .env  | tr -d '"' | grep ROLL_BAR_TOKEN )
export deploy_id=$(git rev-parse HEAD)
curl -H "X-Rollbar-Access-Token: $ROLL_BAR_TOKEN" -H "Content-Type: application/json" -X POST 'https://api.rollbar.com/api/1/deploy' -d '{"environment": "production", "revision": "'"$deploy_id"'", "status": "succeeded"}'

echo "Комит $(git rev-parse HEAD) задеплоен успешно"

