# Generated by Django 3.2.15 on 2022-09-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_rename_phone_order_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
