# Generated by Django 3.2.15 on 2022-09-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, max_length=500, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Новый заказ'), (1, 'Готовится'), (2, 'Передан курьеру'), (3, 'Закрыт')], db_index=True, default=0, verbose_name='Cтатус'),
        ),
    ]
