# Generated by Django 3.2.15 on 2022-09-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_auto_20220916_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Наличными'), (1, 'Электронно')], db_index=True, default=0, verbose_name='Способ оплаты'),
        ),
    ]
