# Generated by Django 3.2.15 on 2022-09-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_auto_20220921_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='lng',
            new_name='lon',
        ),
    ]
