# Generated by Django 3.2.15 on 2022-10-01 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_auto_20220929_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_cook',
        ),
    ]
