# Generated by Django 3.2.15 on 2022-10-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
