# Generated by Django 3.2.15 on 2022-11-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(choices=[(0, 'Наличными'), (1, 'Электронно'), (2, 'Требует уточнения')], db_index=True, default=2, verbose_name='Способ оплаты'),
        ),
    ]
